In [1]:
import soundfile as sf
import numpy as np
import pandas as pd
import glob
import os
sampled_root = '../data/sampled'

In [2]:
df = pd.read_csv('dataHasilConvert.csv')
df

,flac_path,wav_path,format_flac,format_wav,subtype_flac,subtype_wav,sr,duration_s,size_flac_kb,size_wav_kb
0,../data/sampled\0\00\0002114d3f.flac,../data/sampled\0\00\0002114d3f.wav,FLAC,WAV,PCM_16,PCM_16,16000,4.200,67.57,131.29
1,../data/sampled\0\00\00079b49f9.flac,../data/sampled\0\00\00079b49f9.wav,FLAC,WAV,PCM_16,PCM_16,16000,5.400,71.20,168.79
2,../data/sampled\0\00\00084ff1da.flac,../data/sampled\0\00\00084ff1da.wav,FLAC,WAV,PCM_16,PCM_16,16000,7.100,91.39,221.92
3,../data/sampled\0\00\000923633f.flac,../data/sampled\0\00\000923633f.wav,FLAC,WAV,PCM_16,PCM_16,16000,4.100,84.85,128.17
4,../data/sampled\0\00\0009d31e8f.flac,../data/sampled\0\00\0009d31e8f.wav,FLAC,WAV,PCM_16,PCM_16,16000,5.300,96.10,165.67
...,...,...,...,...,...,...,...,...,...,...
18384,../data/sampled\9\9f\9fe3d15862.flac,../data/sampled\9\9f\9fe3d15862.wav,FLAC,WAV,PCM_16,PCM_16,16000,8.800,136.22,275.04
18385,../data/sampled\9\9f\9ff3410471.flac,../data/sampled\9\9f\9ff3410471.wav,FLAC,WAV,PCM_16,PCM_16,16000,5.758,107.56,180.00
18386,../data/sampled\9\9f\9ff6f34230.flac,../data/sampled\9\9f\9ff6f34230.wav,FLAC,WAV,PCM_16,PCM_16,16000,5.500,98.99,171.92
18387,../data/sampled\9\9f\9ff789f862.flac,../data/sampled\9\9f\9ff789f862.wav,FLAC,WAV,PCM_16,PCM_16,16000,3.700,62.33,115.67
18388,../data/sampled\9\9f\9ffc14c748.flac,../data/sampled\9\9f\9ffc14c748.wav,FLAC,WAV,PCM_16,PCM_16,16000,8.200,109.69,256.29

In [3]:
def sampling(wav_path: str) -> tuple[np.ndarray, int]:
    samples, sr = sf.read(wav_path, dtype="float64")

    if samples.ndim == 2:       # stereo jadi mono 
        samples = samples[:, 0]

    return samples, sr

In [4]:
def quantization(samples: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    # Step 1 – level rentang -32768 sampai +32767
    max_level = 32_767
    min_level = -32_768

    # Step 2 – kode PCM: amplitudo kontinu × 32767 kemudian bulatkan
    kode_pcm = np.clip(np.round(samples * max_level), min_level, max_level).astype(int)

    # Step 3 – rekonstruksi kode PCM ÷ 32767 = amplitudo diskrit
    quantized = kode_pcm / max_level

    return kode_pcm, quantized

In [5]:
all_paths = [
    os.path.abspath(os.path.join(root_dir, file))
    for root_dir, dirs, files in os.walk(sampled_root)
    for file in files
]
print(all_paths)

['d:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0002114d3f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00079b49f9.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00084ff1da.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\000923633f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0009d31e8f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\000e2b3102.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\000e78988a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00175a0bc1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00197e04b3.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\001a373938.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\001dcf14f7.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0020c37d51.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00210b8a68.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0023bd2ccf.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\002457231d.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00246a66f9.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\002762f6a1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\002e271120.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0034ac8d52.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00387097cd.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00397dbece.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0039d83618.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\004624c146.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0048f84a2a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\004dccbff4.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\005024d7f2.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00511d2b0b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0052a75aec.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00537fd57f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0054717559.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\005694e761.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\005a3b3ad4.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0060bec0bf.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0064a00864.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0066729efd.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0068baa9c2.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00697a73d8.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00766c0fb7.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0078e9f169.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\007a5e3c52.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\007ce242ac.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\007e9fc35d.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\007f9749b3.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\007fc1364c.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\0081ddf283.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00841bcba2.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00848005e2.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\008ee797fd.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\008fbf2570.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\009b5bb14f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\009f77ca88.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00a16900a7.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00affe5483.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00bc3441b5.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00bf7a03ab.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00c2b01ca8.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00c7313605.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00cd686740.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00d37ddcfb.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00d38e31fe.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00d75105a0.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00d7d99bb0.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00db96d778.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00e0605dc0.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00e1d21cab.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00e1f837f4.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00e49157d1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00e74ac018.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00ea76c876.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00ebe8b269.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00f25618ea.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00f4555fd4.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00f5b294f0.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00f8e1afe4.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\00\\00fe4f679a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0104f22d0c.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\010d57df94.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0110d5fbaa.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0113afa284.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0116650cea.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0117057e80.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0117f0eb18.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\012002d84a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\012b05ebe1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\012d1b449f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0134d96003.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0135102010.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01375715b9.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\013b145d7c.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\013e26735f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\013f3ee823.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0141d2e6d6.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0151aaa5a1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0151ce4c99.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\015448843f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0158009ab8.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\015c4e151b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\015d64de68.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\015f99c31e.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01647e8697.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\016514e4b1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01663277eb.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0166c3f3e1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01680163fd.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0178d3b516.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01799fc421.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\017d31796e.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0182a12a13.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\018b99de0e.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\019185c85f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0191ea17b1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\0192c934dd.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\019765dce6.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01995f5ab5.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\019a9df0eb.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01a357ef3c.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01a635ba39.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01b2816762.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01b39b5781.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01b68fab63.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01bf2206f0.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01c0b88e5f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01c4660b58.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01cc659ebe.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01cdd22dd3.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01ce30c452.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01cecdc33e.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01d5f5b38c.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01d7e19a59.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01d88f352f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01da1f8933.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01dedb9ede.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01df29635a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01e20a3203.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01e4b03bcf.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01e9a705b8.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01ed57598b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01eee07a20.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01ef8dcd79.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01eff34f82.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01f1fc23d4.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01f54d7e7f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01fda6a160.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\01\\01ffe1dbec.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\020056053a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02018735c8.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\020274a14a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0207155dcf.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02075c1e48.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0213fd9670.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\021569ad74.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02163a8c44.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0217022e93.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0218741f16.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\021a93fb24.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02205c5d28.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0221a02ba4.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\022354aff2.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0224c2241a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0225c039be.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02316c6b40.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\023334a01a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0234536a2f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0234a5d921.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0239eb7457.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\023fe38629.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\023fffbe09.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02445aadc5.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0247a86e23.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02486d1c5e.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\024ab2ab1b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\024de7a0ef.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\024e2f6fa9.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\024f8cf7c6.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\025334a0f1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0253957aaf.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\025c8d5127.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\025e51b5da.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\026050b4cc.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02622334c1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0266c26886.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\026abdd127.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02730b8862.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0276992af7.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\027e593253.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02854f61a6.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0289a0f9e5.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\028a29cd5b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02910de881.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\0291abf422.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02971e3a2b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\029b5dfe5f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\029c36820d.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\029fac7d41.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02a2f1ea14.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02a663e3b3.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02abb5dcc7.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02ad427ddc.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02ae257339.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02b2723e38.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02b6e9fffb.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02b7ba4113.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02bb97f002.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02c599eaa2.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02c96b8973.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02cb7b7de5.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02cba8a992.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02d50e107f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02d83dd078.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02db44f7bf.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02df8f533a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02e306c9b6.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02e7ce5665.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02ee9c1c5b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02f43be032.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02f6f5bb58.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02f87902ce.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02f9707bb5.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02fbef0d62.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\02\\02fc813594.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0300a3c010.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0303954d94.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\030abcd9a1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03135f7438.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03150c758f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03170189f0.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03194c8854.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\031c2cbb75.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\031cb3ba0c.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\031d7bfcc3.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\032290c391.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0322d4c7d0.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03231e74df.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\032321769e.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0328347395.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0330821cab.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\033300a736.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03370a6527.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\033a90c34d.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\033b056750.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\033f249730.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\034020edf5.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0340841c6b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0346a196f3.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03475263f9.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\034f2379e3.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0351ca6516.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\035232062a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03545e9923.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0356997850.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\035820e095.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\035cfe6211.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0361a12f8c.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\036528987b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0379a6dddf.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\037daebbfc.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0382a9564b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\038d43b2d1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0392964699.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03968b7ed4.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03988eb9c1.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\0399d936f4.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\039b878800.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03a01d3246.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03a02efafd.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03a2b9a4d3.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03a5b77b43.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03a8fd785d.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03aa694f7f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03ae1cea83.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03afc46f1b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03b127512b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03b3210c8b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03b53ffe32.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03b575537f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03c04e0487.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03c7cb827f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03c8741953.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03c89107bf.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03cac0021a.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03cff26b3f.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03d4683a37.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03d5445e02.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03eba7e22b.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03ed157905.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03ed80c097.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03efcb2f83.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03f0f9e1c4.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03f5372b4c.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03f6ac1585.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\03\\03fde01e37.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\04\\04016bca86.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\04\\04020b476e.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\04\\040e1bb165.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\04\\0410a92371.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\04\\0412f471a8.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\04\\04132c25ae.wav', 'd:\\doc\\2026\\FINAL CODE\\data\\sampled\\0\\04\\0413c72f05.wav', 'd:\\doc\\2026\\FINAL CODE\\data\

In [6]:
hasil_quantization = []
hasil_sampling =[]
for wav_path in glob.glob(os.path.join(sampled_root, "**/*.wav"), recursive=True):
    
    samples, sr = sampling(wav_path)

    kode_pcm, quantized = quantization(samples)
    wave = os.path.splitext(os.path.basename(wav_path))[0]
    hasil_sampling.append({
                "Id"   : wave,
                "Sample Rate" : f" {sr} Hz",
                "Jumlah Sampel" : f"{len(samples)}",
                "Durasi"     : f"{len(samples)/sr:.3f} detik",
                "Contoh Sampling" : (samples[:5])
            })

    hasil_quantization.append({
        "Id"      : wave,
        "Sample Rate" : f" {sr} Hz",
        "Jumlah Sampel" : f"{len(samples)}",
        "Durasi"     : f"{len(samples)/sr:.3f} detik",
        "Contoh Sampling"   : samples[:5].tolist(),     # amplitudo kontinu
        "Contoh kode PCM"   : kode_pcm[:5].tolist(),   # hasil step 2
        "Contoh Quantized"  : quantized[:5].tolist(),  # hasil step 3
    })
df_sampling = pd.DataFrame(hasil_sampling)
df_sampling.to_csv("HasilSampling.csv", index=False)
df_quantization = pd.DataFrame(hasil_quantization)
df_quantization.to_csv("HasilQuantization.csv", index=False)

In [7]:
df_sampling

,Id,Sample Rate,Jumlah Sampel,Durasi,Contoh Sampling
0,0002114d3f,16000 Hz,67200,4.200 detik,"[-0.00201416015625, -0.002349853515625, -0.002..."
1,00079b49f9,16000 Hz,86400,5.400 detik,"[-0.00067138671875, -0.000762939453125, -0.001..."
2,00084ff1da,16000 Hz,113600,7.100 detik,"[0.0001220703125, 0.0001220703125, 6.103515625..."
3,000923633f,16000 Hz,65600,4.100 detik,"[0.005279541015625, 0.001953125, 0.00192260742..."
4,0009d31e8f,16000 Hz,84800,5.300 detik,"[0.002105712890625, 0.003204345703125, 0.00408..."
...,...,...,...,...,...
18384,9fe3d15862,16000 Hz,140800,8.800 detik,"[0.0008544921875, 0.00146484375, 0.00164794921..."
18385,9ff3410471,16000 Hz,92136,5.758 detik,"[0.00146484375, 0.0050048828125, -0.0017395019..."
18386,9ff6f34230,16000 Hz,88000,5.500 detik,"[0.0020751953125, 0.0023193359375, 0.001739501..."
18387,9ff789f862,16000 Hz,59200,3.700 detik,"[0.000701904296875, 0.00079345703125, 0.001037..."
18388,9ffc14c748,16000 Hz,131200,8.200 detik,"[-0.001312255859375, -0.000946044921875, -0.00..."

In [8]:
df_quantization

,Id,Sample Rate,Jumlah Sampel,Durasi,Contoh Sampling,Contoh kode PCM,Contoh Quantized
0,0002114d3f,16000 Hz,67200,4.200 detik,"[-0.00201416015625, -0.002349853515625, -0.002...","[-66, -77, -69, -35, -10]","[-0.0020142216254158147, -0.002349925229651784..."
1,00079b49f9,16000 Hz,86400,5.400 detik,"[-0.00067138671875, -0.000762939453125, -0.001...","[-22, -25, -35, -34, -31]","[-0.0006714072084719382, -0.000762962736899929..."
2,00084ff1da,16000 Hz,113600,7.100 detik,"[0.0001220703125, 0.0001220703125, 6.103515625...","[4, 4, 2, 13, 10]","[0.00012207403790398877, 0.0001220740379039887..."
3,000923633f,16000 Hz,65600,4.100 detik,"[0.005279541015625, 0.001953125, 0.00192260742...","[173, 64, 63, 136, 195]","[0.005279702139347514, 0.0019531846064638203, ..."
4,0009d31e8f,16000 Hz,84800,5.300 detik,"[0.002105712890625, 0.003204345703125, 0.00408...","[69, 105, 134, 181, 201]","[0.0021057771538438063, 0.003204443494979705, ..."
...,...,...,...,...,...,...,...
18384,9fe3d15862,16000 Hz,140800,8.800 detik,"[0.0008544921875, 0.00146484375, 0.00164794921...","[28, 48, 54, 82, 113]","[0.0008545182653279214, 0.0014648884548478652,..."
18385,9ff3410471,16000 Hz,92136,5.758 detik,"[0.00146484375, 0.0050048828125, -0.0017395019...","[48, 164, -57, -381, -430]","[0.0014648884548478652, 0.0050050355540635395,..."
18386,9ff6f34230,16000 Hz,88000,5.500 detik,"[0.0020751953125, 0.0023193359375, 0.001739501...","[68, 76, 57, 68, 80]","[0.002075258644367809, 0.0023194067201757866, ..."
18387,9ff789f862,16000 Hz,59200,3.700 detik,"[0.000701904296875, 0.00079345703125, 0.001037...","[23, 26, 34, 17, 33]","[0.0007019257179479354, 0.000793481246375927, ..."
18388,9ffc14c748,16000 Hz,131200,8.200 detik,"[-0.001312255859375, -0.000946044921875, -0.00...","[-43, -31, -30, -37, -25]","[-0.0013122959074678793, -0.000946073793755913..."

In [ ]:
def voice_activity_detection(
    quantized  : np.ndarray,
    sr         : int,
    frame_ms   : int = 300,     # durasi frame: 300 ms menghasilkan 480 sampel (dokumen)
    snr_min    : float = 6.0,   # ambang batas bawah  (dokumen)
    snr_max    : float = 10.0,  # ambang batas atas   (dokumen)
) -> tuple[np.ndarray, list[dict]]:

    #Bagi sinyal menjadi frame 
    frame_size = int(sr * frame_ms / 1000)      # 16000 * 300/1000 = 480
    frames     = [
        quantized[i : i + frame_size]
        for i in range(0, len(quantized), frame_size)
        if len(quantized[i : i + frame_size]) == frame_size  # buang frame tidak lengkap
    ]

    frame_results = []
    voice_frames  = []

    for idx, frame in enumerate(frames):

        # Step 1: Hitung Energi per Frame 
        # Dokumen: "Setiap nilai amplitudo diskrit dipangkatkan dan ditotalkan"
        # ∑x² = 0,0000001341 + ... + 0,0000004107 = 0,0000026934
        energi = np.sum(frame ** 2)

        # Step 2: Perhitungan Daya 
        # Dokumen: P = ∑x² / N  =  0,0000026934 / 20  = 0,0000001347
        N    = len(frame)
        daya = energi / N

        # Step 3: Estimasi Daya 
        # Dokumen: P = (1/32767)² / 12  =  0,0000000009 / 12  = 0,0000000001
        delta         = 1 / 32_767
        estimasi_daya = (delta ** 2) / 12

        # Step 4: Rasio Signal to Noise
        # Dokumen: SNR = daya / estimasi_daya  =  0,0000001347 / 0,0000000001  = 1735,2
        snr = daya / estimasi_daya if estimasi_daya > 0 else 0

        # Step 5: Konversi SNR ke Logaritmik (dB) 
        # Dokumen: SNR = 10 × log10(1735,2)  =  3,2393495390
        snr_db = 10 * np.log10(snr) if snr > 0 else 0

        # Step 6: Perbandingan terhadap Ambang Batas 
        # Dokumen: ambang batas 6 - 10
        # SNR > snr_max -> frame wicara
        # SNR < snr_min -> frame noise
        if snr_db > snr_max:
            label = "wicara"
            voice_frames.append(frame)
        elif snr_db < snr_min:
            label = "noise"
        else:
            label = "tidak pasti"

        frame_results.append({
            "frame_idx"    : idx,
            "energi"       : round(energi, 10),
            "daya"         : round(daya, 10),
            "estimasi_daya": round(estimasi_daya, 10),
            "snr"          : round(snr, 4),
            "snr_db"       : round(snr_db, 10),
            "label"        : label,
        })

    # Gabungkan semua frame wicara menjadi satu sinyal bersih
    sinyal_bersih = np.concatenate(voice_frames) if voice_frames else np.array([])

    return sinyal_bersih, frame_results

In [12]:
hasil_sampling     = []
hasil_quantization = []
hasil_vad          = []

for wav_path in glob.glob(os.path.join(sampled_root, "**/*.wav"), recursive=True):
    try:
        audio_id = os.path.splitext(os.path.basename(wav_path))[0]

        # SAMPLING 
        samples, sr = sampling(wav_path)

        hasil_sampling.append({
            "Id"              : audio_id,
            "Sample Rate"     : f"{sr} Hz",
            "Jumlah Sampel"   : len(samples),
            "Durasi"          : f"{len(samples)/sr:.3f} detik",
            "Contoh Sampling" : samples[:5].tolist(),
        })

        # QUANTIZATION 
        kode_pcm, quantized = quantization(samples)

        hasil_quantization.append({
            "Id"              : audio_id,
            "Sample Rate"     : f"{sr} Hz",
            "Jumlah Sampel"   : len(samples),
            "Durasi"          : f"{len(samples)/sr:.3f} detik",
            "Contoh Sampling" : samples[:5].tolist(),
            "Contoh Kode PCM" : kode_pcm[:5].tolist(),
            "Contoh Quantized": quantized[:5].tolist(),
        })

        # VOICE ACTIVITY DETECTION 
        sinyal_bersih, frame_results = voice_activity_detection(quantized, sr)

        df_frame = pd.DataFrame(frame_results)
        hasil_vad.append({
            "Id"             : audio_id,
            "Total Frame"    : len(frame_results),
            "Frame Wicara"   : df_frame[df_frame["label"] == "wicara"].shape[0],
            "Frame Noise"    : df_frame[df_frame["label"] == "noise"].shape[0],
            "Frame Tdk Pasti": df_frame[df_frame["label"] == "tidak pasti"].shape[0],
            "Sinyal Bersih"  : sinyal_bersih[:5].tolist() if len(sinyal_bersih) > 0 else [],
        })
    except Exception as e:
        print(f"Error pada file : {wav_path} : {e}")

df_sampling     = pd.DataFrame(hasil_sampling)
df_quantization = pd.DataFrame(hasil_quantization)
df_vad          = pd.DataFrame(hasil_vad)

df_sampling.to_csv("HasilSampling.csv",     index=False)
df_quantization.to_csv("HasilQuantization.csv", index=False)
df_vad.to_csv("HasilVAD.csv",               index=False)

print(f"\n{'='*40}")
print(f"HasilSampling.csv     -> {len(df_sampling)} file")
print(f"HasilQuantization.csv -> {len(df_quantization)} file")
print(f"HasilVAD.csv          -> {len(df_vad)} file")

Error pada file : ../data/sampled\5\59\5980ab3cf8.wav : 'label'

========================================
HasilSampling.csv     -> 18389 file
HasilQuantization.csv -> 18389 file
HasilVAD.csv          -> 18388 file

In [14]:
df_vad

,Id,Total Frame,Frame Wicara,Frame Noise,Frame Tdk Pasti,Sinyal Bersih
0,0002114d3f,14,14,0,0,"[-0.0020142216254158147, -0.002349925229651784..."
1,00079b49f9,18,18,0,0,"[-0.0006714072084719382, -0.000762962736899929..."
2,00084ff1da,23,23,0,0,"[0.00012207403790398877, 0.0001220740379039887..."
3,000923633f,13,13,0,0,"[0.005279702139347514, 0.0019531846064638203, ..."
4,0009d31e8f,17,17,0,0,"[0.0021057771538438063, 0.003204443494979705, ..."
...,...,...,...,...,...,...
18383,9fe3d15862,29,29,0,0,"[0.0008545182653279214, 0.0014648884548478652,..."
18384,9ff3410471,19,19,0,0,"[0.0014648884548478652, 0.0050050355540635395,..."
18385,9ff6f34230,18,18,0,0,"[0.002075258644367809, 0.0023194067201757866, ..."
18386,9ff789f862,12,12,0,0,"[0.0007019257179479354, 0.000793481246375927, ..."
18387,9ffc14c748,27,27,0,0,"[-0.0013122959074678793, -0.000946073793755913..."